Repository newrelic/node-newrelic-mysql, pull requests merged in 2020-08, with the labels that each got.

#28 Migrates CI to GitHub Actions.
  .github/workflows/ci-workflow.yml
  .travis.yml
Labels: risk:low, semver:patch

#29 Update license
  LICENSE
  package.json
Labels: risk:none, semver:patch

#30 Bump newrelic/test-utilities to open source version
  package.json
Labels: ready for review, risk:low, semver:patch

#31 Add copyright text
  index.js
  lib/instrumentation.js
  nr-hooks.js
  tests/versioned/common/basic-pool.js
  tests/versioned/common/basic.js
  tests/versioned/common/pooling.js
  tests/versioned/common/setup.js
  tests/versioned/common/transactions.js
  tests/versioned/mysql/basic-pool.tap.js
  tests/versioned/mysql/basic.tap.js
  tests/versioned/mysql/newrelic.js
  tests/versioned/mysql/pooling.tap.js
  tests/versioned/mysql/transactions.tap.js
  tests/versioned/mysql2/basic-pool.tap.js
  tests/versioned/mysql2/basic.tap.js
  tests/versioned/mysql2/newrelic.js
  tests/versioned/mysql2/pooling.tap.js
  tests/versioned/mysql2/promises.tap.js
  tests/versioned/mysql2/transactions.tap.js
Labels: risk:none, semver:patch

#32 Added GitHub issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
Labels: ready for review, risk:low, semver:patch

#33 Added PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready for review, risk:low, semver:patch

#34 Added code of conduct file
  CODE_OF_CONDUCT.md
Labels: ready for review, risk:low, semver:patch

#35 Remove coveralls badges from readme
  README.md
Labels: risk:none, semver:patch

#36 Add third party notices
  THIRD_PARTY_NOTICES.md
  package.json
  third_party_manifest.json
Labels: risk:none, semver:patch

#37 Updated README
  README.md
  package.json
Labels: ready for review, risk:none, semver:patch

#38 Add Contributing guidelines and update third party notices
  CONTRIBUTING.md
  THIRD_PARTY_NOTICES.md
Labels: risk:none, semver:patch

#39 Merge OS main into main
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/troubleshooting.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  THIRD_PARTY_NOTICES.md
  index.js
  lib/instrumentation.js
  nr-hooks.js
  package.json
  tests/versioned/common/basic-pool.js
  tests/versioned/common/basic.js
  tests/versioned/common/pooling.js
  tests/versioned/common/setup.js
  tests/versioned/common/transactions.js
  tests/versioned/mysql/basic-pool.tap.js
  tests/versioned/mysql/basic.tap.js
  tests/versioned/mysql/newrelic.js
  tests/versioned/mysql/pooling.tap.js
  tests/versioned/mysql/transactions.tap.js
  tests/versioned/mysql2/basic-pool.tap.js
  tests/versioned/mysql2/basic.tap.js
  tests/versioned/mysql2/newrelic.js
  tests/versioned/mysql2/pooling.tap.js
  tests/versioned/mysql2/promises.tap.js
  tests/versioned/mysql2/transactions.tap.js
  third_party_manifest.json
Labels: risk:low, semver:major

#40 Update readme
  README.md
Labels: risk:none, semver:patch

#41 update node-agent peer dependency
  package.json
Labels: risk:none, semver:major

#42 v4.0.0 release
  CHANGELOG.md
Labels: risk:low, semver:major

#43 Update npmignore
  .npmignore
Labels: risk:none, semver:patch
